# data
data:
  eval_data: "/workspace/manifests/eval.jsonl"
  shuffle: true
  train_data: "/workspace/manifests/train.jsonl"


# model
moshi_paths:
  hf_repo_id: "kyutai/moshiko-pytorch-bf16"
full_finetuning: true
lora:
  enable: false
  rank: 128
  scaling: 2.
  ft_embed: false
first_codebook_weight_multiplier: 100.
text_padding_weight: .5


# optim
duration_sec: 163.84
batch_size: 2
num_microbatches: 2
max_steps: 351
gradient_checkpointing: true
optim:
  lr: 2e-6
  weight_decay: 0.1
  pct_start: 0.14


# other
seed: 42
log_freq: 1
eval_freq: 39
do_eval: true
do_ckpt: true
ckpt_freq: 39
save_adapters: false
run_dir: "/workspace/moshi-ft-models/english-orig-run0"
overwrite_run_dir: true


wandb:
  project: "moshi_pre_training_english_new_code"
  run_name: "new_code_test_run_10hrs"